-- 이 프로젝트의 스키마 정본. 여기부터는 엔티티가 아니라 이 디렉토리가 스키마를 정한다.
--
-- 내용은 Hibernate 의 ddl-auto 가 만들어온 스키마와 같다. 다만 그대로 뜨지 않고 다시 적었다 —
-- pg_dump 는 identity 를 ALTER 로 떼어내고 제약 이름을 해시로 남기는데, 사람도 jOOQ 파서도
-- 읽기 어렵다. 어긋나지 않는다는 보장은 SchemaMigrationTest 가 한다(진짜 PostgreSQL + validate).

-- 로그인한 사람. 신원(구글 계정 등)은 user_identities 가 따로 갖는다.
CREATE TABLE users (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         uuid                        NOT NULL,
    display_name varchar(255)                NOT NULL,
    status       varchar(255)                NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL,
    updated_at   timestamp(6) with time zone NOT NULL,

    -- 바깥에 내보내는 식별자. id 는 내부에서만 쓴다.
    CONSTRAINT uk_users_uuid UNIQUE (uuid),
    -- 값이 늘면 이 제약도 같이 고쳐야 한다. ddl-auto 는 이것을 갱신하지 못한다.
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

-- 한 사람이 여러 provider 로 로그인할 수 있다. (issuer, subject) 한 쌍이 곧 하나의 신원이다.
CREATE TABLE user_identities (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint                      NOT NULL,
    issuer        varchar(255)                NOT NULL,
    subject       varchar(255)                NOT NULL,
    email         varchar(255),
    linked_at     timestamp(6) with time zone NOT NULL,
    last_login_at timestamp(6) with time zone,

    CONSTRAINT uk_user_identities_issuer_subject UNIQUE (issuer, subject),
    CONSTRAINT fk_user_identities_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 생성 요청 한 건. 무엇을 만들지는 option 이, 몇 장인지는 task_count 가 말한다.
CREATE TABLE generation_jobs (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           uuid                        NOT NULL,
    owner_user_id  bigint                      NOT NULL,
    -- 생성 종류마다 필드가 달라 컬럼으로 쪼개지 않는다. 판별자는 JSON 안의 type 이다.
    option         jsonb                       NOT NULL,
    model          varchar(255)                NOT NULL,
    task_count     integer                     NOT NULL,
    status         varchar(255)                NOT NULL,
    -- Task 를 만들기도 전에 실패한 경우의 사유. Task 개별 실패는 Task 가 갖는다.
    failure_reason varchar(255),
    created_at     timestamp(6) with time zone NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL,

    CONSTRAINT uk_generation_jobs_uuid UNIQUE (uuid),
    -- CLOSED 는 "성공" 이 아니라 "더 움직이지 않는다" 는 뜻이다.
    CONSTRAINT ck_generation_jobs_status CHECK (status IN ('PENDING', 'DISPATCHED', 'CLOSED'))
);

-- Provider 호출 한 번. 이미지 N 장이면 Task 도 N 개다.
CREATE TABLE generation_job_tasks (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             uuid                        NOT NULL,
    job_id           bigint                      NOT NULL,
    -- Job 안에서 몇 번째 작업인가. 요청한 장수만큼만 만들어지도록 아래 제약이 지킨다.
    sequence         integer                     NOT NULL,
    status           varchar(255)                NOT NULL,
    -- 재시도 상한 판단에 쓴다.
    attempt_count    integer                     NOT NULL,
    provider_task_id varchar(255),
    failure_reason   varchar(255),
    created_at       timestamp(6) with time zone NOT NULL,

    CONSTRAINT uk_job_tasks_uuid UNIQUE (uuid),
    CONSTRAINT uk_job_tasks_job_seq UNIQUE (job_id, sequence),
    CONSTRAINT ck_job_tasks_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED'))
);

-- 실제로 만들어진 파일. 보관소에는 바이트만 있고, 그게 무엇인지는 이 행이 안다.
CREATE TABLE generated_files (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        uuid                        NOT NULL,
    task_id     bigint                      NOT NULL,
    -- 보관소에서의 위치. uuid 로부터 만들어져 한 Task 가 파일을 몇 개 내든 겹치지 않는다.
    storage_key varchar(255)                NOT NULL,
    -- 가로·세로·형식·크기. 이 값으로 검색하거나 집계할 일이 없어 컬럼으로 쪼개지 않는다.
    metadata    jsonb                       NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,

    CONSTRAINT uk_generated_files_uuid UNIQUE (uuid)
);

-- 유니크 제약을 걸지 않는다. "같은 Task 가 두 번 성공 처리되지 않는다" 는 Task 의 불변식이라
-- Task 의 상태 전이가 지켜야 한다. 인덱스는 Job 조회가 Task 별로 파일을 모을 때 쓴다.
CREATE INDEX idx_generated_files_task ON generated_files (task_id);
