-- Provider 호출 한 번의 기록. 성공도 실패도 한 행이다 —
-- 실패한 호출도 시간을 쓰고, 타임아웃처럼 돈까지 쓰는 경우가 있다.
-- 그래서 이름이 usage 가 아니라 calls 다. 지출의 단위는 사용량이 아니라 호출이다.
--
-- append-only 다. 한 번 적힌 행은 cost_* 를 채우는 것 말고는 바뀌지 않는다.
--
-- generation 의 행을 대리키가 아니라 uuid 로 가리키고 FK 도 두지 않는다.
-- 그 근거는 V2 와 GenerationJob.ownerUserUuid 의 KDoc 에 있다.
-- 여기서는 이유가 하나 더 있다 — FK 는 실패할 수 있는 제약이고,
-- 이 INSERT 는 이미 돈을 쓴 뒤에 일어나므로 실패하면 안 된다.
CREATE TABLE provider_calls (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               uuid                        NOT NULL,

    task_uuid          uuid                        NOT NULL,
    job_uuid           uuid                        NOT NULL,
    -- 집계 축이라 여기 복사한다. 원장은 조인 없이 답할 수 있어야 하고, Job 이 지워져도 남아야 한다.
    owner_user_uuid    uuid                        NOT NULL,

    provider           varchar(255)                NOT NULL,
    model              varchar(255)                NOT NULL,

    -- Provider 에게 **실제로 보낸** 요청. 적힌 `16:9 @ 2k` 가 아니라 그것을 푼 `2048x1152` 다.
    -- 토큰을 주지 않고 크기·품질이 곧 단가인 Provider 에서는 이것이 유일한 계산 근거가 된다.
    --
    -- 컬럼으로 쪼개지 않는 이유는 **생성 종류마다 축이 다르기** 때문이다. 이미지는 픽셀과 품질이지만
    -- 영상은 길이와 프레임이다. 컬럼이면 종류가 늘 때마다 다른 종류의 행에 null 인 칸이 생기고,
    -- 그 null 은 "모른다" 가 아니라 "해당 없음" 이라 뜻이 섞인다.
    -- generation_jobs.option 이 JSON 인 것과 같은 이유다 — 이건 그것을 픽셀로 푼 결과다.
    --
    -- 판별자는 JSON 안의 type 이고 그 값이 행에 그대로 박힌다. 리네임하면 옛 행을 못 읽는다.
    request            jsonb,

    succeeded          boolean                     NOT NULL,
    failure_reason     varchar(255),
    -- Provider 호출만의 시간. 보관 지연이 섞이면 Provider 성능 비교가 안 된다.
    latency_ms         integer                     NOT NULL,

    -- 응답의 사용량 블록 원문. 우리 포맷으로 접지 않으므로 외부 필드명이 그대로 들어 있다.
    -- 모양이 Provider 마다 달라 컬럼으로 쪼갤 수가 없다 — 토큰을 주는 곳, 크레딧을 주는 곳,
    -- 아무것도 안 주는 곳이 한 표에 들어온다. 집계는 이 컬럼이 아니라 cost_usd 가 받는다.
    usage_raw          jsonb,

    -- Provider 가 비용을 **직접 답한** 경우만 채운다. 토큰 수는 여기 오지 않는다(usage_raw 에 있다).
    reported_amount    numeric(18, 8),
    reported_unit      varchar(32),

    -- 달러로 환산한 비용. Provider 이질성을 가로지르는 유일한 공통 축이라 컬럼으로 뺀다.
    -- 반올림하지 않는다 — 호출당 $0.00019 를 센트로 접으면 0 이 되고 백 건을 더해도 0 이다.
    cost_usd           numeric(18, 8),
    -- NULL 이 곧 "모른다" 다. UNKNOWN 값을 따로 두지 않는다.
    -- 이 컬럼은 라벨이 아니라 소급 재계산의 필터다 — REPORTED 행을 덮어쓰지 않기 위한 것.
    cost_basis         varchar(32),
    price_book_version varchar(32),

    -- 단가는 시간에 따라 바뀐다. 이 값이 없으면 "그때의 단가" 를 고를 수 없다.
    called_at          timestamp(6) with time zone NOT NULL,

    CONSTRAINT uk_provider_calls_uuid UNIQUE (uuid),
    -- 값이 늘면 이 제약도 같이 고쳐야 한다. ddl-auto 는 이것을 갱신하지 못한다.
    CONSTRAINT ck_provider_calls_basis CHECK (cost_basis IN ('REPORTED', 'DERIVED', 'ESTIMATED')),
    CONSTRAINT ck_provider_calls_unit CHECK (reported_unit IN ('USD', 'PROVIDER_CREDIT'))
);

-- "이 사람이 이번 달 얼마 썼나" 가 이 표의 주된 질문이다.
CREATE INDEX idx_provider_calls_owner_called ON provider_calls (owner_user_uuid, called_at);

-- task_uuid 에 유니크를 걸지 않는다. 재시도하면 같은 Task 가 여러 번 호출되고,
-- 그 각각이 따로 돈을 쓴다 — 한 행으로 접으면 합계가 실제보다 적어진다.
CREATE INDEX idx_provider_calls_task ON provider_calls (task_uuid);
